export const hadislar = [
  "1. Ilmning ofati - esdan chiqarmoqlik va ilmga rag’bati bo’lmagan kishilarga o’rgatib, uni zoye ketkazmoqlikdir. ",
  "2. Qizlarni turmushga chiqarish to’g’risida onalari bilan maslahatlashinglar.        ",
  "3. Munofiqlik belgisi uchtadir: yolg’on so’zlash, va’dasining ustidan chiqmaslik va omonatga xiyonat qilish",
  "4. Chaqirilgan joygagina boring. ",
  "6. Halol va ruxsat etilgan narsalar ichida Tangriga xush kelmaydigani - taloqdir.   ",
  "7. Odamlar ichida Tangriga yoqimsizrog’i - ashaddiy dushmanlik qiluvchidir.   ",
  "8. Bid’at-xurofotga berilgan odam to ularni tark etmaguncha, uning qilgan savobli ishlarini Tangri qabul qilmaydi. ",
  "9. Taomni sovitibroq iste’mol qilinglar, issiq-qaynoq taomda baraka bo’lmaydi.   ",
  "10. Har bir qavmning qiz farzandidan tug’ilgan bola ham shu qavmga mansubdir. ",
  "13. Qo’y boqinglar, chunki u barakadir.   ",
  "23. Tangri nazdida eng yaxshi gap - rost gapdir.   ",
  "21. Odamlarni yuziga urishdan saqlaninglar.   ",
  "22. Aroqdan saqlaninglar, chunki u barcha yomonliklarning kalitidir.  ",
  "23. Tangri nazdida eng yaxshi gap - rost gapdir.   ",
  "24. Tangri nazdida eng ma’qul jihod18 - zolim podshohga aytilgan haq so’zdir.   ",
  "25. Tangri nazdida bandalarning eng yaxshisi o’z ahli-ayoliga foydasi ko’p tegadigan kishidir.   ",
  "277. Qasam ichish uni buzib qo’yish yoki nadomatdan xoli emas.   ",
  "278. Ne’matga shukr qilish uning zavolidan omon saqlaydi. ",
  "297. Mo’minlarning yaxshisi – uning qo’li va tilidan boshqalar ozor topmaydiganidir.   ",
  "351. Oxir zamondagi mulklarning yomoni – bu qullardir.   ",
  ""
  ];
