export const hadislar = [
  "1. Ilmning ofati - esdan chiqarmoqlik va ilmga rag’bati bo’lmagan kishilarga o’rgatib, uni zoye ketkazmoqlikdir. ",
  "2. Qizlarni turmushga chiqarish to’g’risida onalari bilan maslahatlashinglar.        ",
  "3. Munofiqlik belgisi uchtadir: yolg’on so’zlash, va’dasining ustidan chiqmaslik va omonatga xiyonat qilish",
  "4. Chaqirilgan joygagina boring. ",
  "6. Halol va ruxsat etilgan narsalar ichida Tangriga xush kelmaydigani - taloqdir.   ",
  "7. Odamlar ichida Tangriga yoqimsizrog’i - ashaddiy dushmanlik qiluvchidir.   ",
  "8. Bid’at-xurofotga berilgan odam to ularni tark etmaguncha, uning qilgan savobli ishlarini Tangri qabul qilmaydi. ",
  "9. Taomni sovitibroq iste’mol qilinglar, issiq-qaynoq taomda baraka bo’lmaydi.   ",
  "10. Har bir qavmning qiz farzandidan tug’ilgan bola ham shu qavmga mansubdir. ",
  "13. Qo’y boqinglar, chunki u barakadir.   ",
  "23. Tangri nazdida eng yaxshi gap - rost gapdir.   ",
  "21. Odamlarni yuziga urishdan saqlaninglar.   ",
  "22. Aroqdan saqlaninglar, chunki u barcha yomonliklarning kalitidir.  ",
  "23. Tangri nazdida eng yaxshi gap - rost gapdir.   ",
  "24. Tangri nazdida eng ma’qul jihod18 - zolim podshohga aytilgan haq so’zdir.   ",
  "25. Tangri nazdida bandalarning eng yaxshisi o’z ahli-ayoliga foydasi ko’p tegadigan kishidir.   ",
  "277. Qasam ichish uni buzib qo’yish yoki nadomatdan xoli emas.   ",
  "278. Ne’matga shukr qilish uning zavolidan omon saqlaydi. ",
  "297. Mo’minlarning yaxshisi – uning qo’li va tilidan boshqalar ozor topmaydiganidir.   ",
  "351. Oxir zamondagi mulklarning yomoni – bu qullardir.   ",
  "Umar ibn Xattobdan  rivoyat qilinadi. Rasululloh sollallohu alayhi vasallam aytdilar: «Albatta, amallar niyat bilandir. Har bir kishi niyat qiluvchidir. Kimning hijrati Alloh va rasuli uchun bo‘lsa, bas, Alloh va rasuli uchun hijrat qilibdi. Kimning hijrati dunyoga yetishish yoki xotinga uylanish uchun bo‘lsa, uning hijrati o‘sha narsaga bo‘libdi».",
  "Oishadan (r.a.)  rivoyat qilinadi. Rasululloh sollallohu alayhi vasallam: «Kimki bizning ishimizda yangilik qilsa, bu undan bo‘lmasa, bas, u rad qilingandir», dedilar. Imom Buxoriy va Muslim  rivoyatlari.",
  "Nu’mon ibn Bashirdan (r.a.)  rivoyat qilinadi. Rasululloh sollallohu alayhi vasallam: «Albatta halol ochiq-ravshan. Albatta harom ochiq-ravshan. Uning o‘rtasida shubhali narsalar bo‘lib, uni ko‘p insonlar bilishmaydi. Kimki shubhadan taqvo qilsa, dini va obro‘sini soflabdi. Kimki shubhaga voqe’ bo‘lsa, haromga yo‘liqibdi. Rioya qiluvchi qo‘riqxona atrofiga borib, uning ichiga kirib qolishi mumkin. Har bir podshohning qo‘riqxonasi bor. Ogoh bo‘ling, Allohning qo‘riqxonasi U harom qilgan narsalardir. Ogoh bo‘ling, jasadda bir parcha go‘sht bor. Agar u isloh bo‘lsa, jasadning barchasi isloh bo‘ladi. Agar u fasod bo‘lsa, jasadning barchasi fasod bo‘ladi. U ham bo‘lsa qalbdir», dedilar. Imom Buxoriy va Muslim  rivoyatlari.",
  "Ibn Mas’uddan (r.a.)  rivoyat qilinadi. Rasululloh sollallohu alayhi vasallam: «Sizlardan biringiz onasi qornida ekanida qirq kun maniy holatida xalq qilinishi jamlanadi. So‘ngra quyuq qon bo‘lib, o‘sha kabi xalq qilinishi jamlanadi. So‘ngra parcha go‘sht bo‘lib, o‘sha kabi xalq qilinishi jamlanadi. So‘ngra farishta yuborilib, unga ruh puflaydi. Va to‘rt kalima, ya’ni rizqi, ajali, amali, baxtli yoki baxtsizligini yozish buyuriladi. Undan boshqa iloh yo‘q bo‘lgan Zot ila qasamki, sizlardan biringiz jannat ahlining amalini qiladi. Hattoki, u bilan jannat orasida bir gaz (o‘lchov) qoladi. Bas, uning o‘sha yozilgan kitobi ilgarilaydi-da, u do‘zax ahlining amalini qilib, do‘zaxga kirib ketadi. Sizlardan biringiz do‘zax ahlining amalini qiladi-da, hattoki u bilan do‘zax orasida bir gaz qoladi. Bas, uning kitobi ilgarilaydi-da, u jannat ahli amalini qilib, jannatga kirib ketadi», dedilar. Imom Buxoriy va Muslim  rivoyatlari.",
  "Hasan ibn Alidan (r.a.)  rivoyat qilinadi. Rasululloh sollallohu alayhi vasallam: «Shubhali narsani shubhasiziga qo‘y», dedilar. (Ya’ni, shubhali narsani tark qilib, shubhasiz narsani ol.) Termiziy va Nasaiy  rivoyatlari.",
  "",
  "",
  "",
  "",
  "",
];
