export const Oyatlar = [
  "“O‘qing (ey, Muhammad! Butun borliqni) yaratgan zot bo‘lmish Rabbingiz ismi bilan! (U) insonni laxta qondan yaratdi. O‘qing! Rabbingiz esa karamlidir. U insonga qalam bilan (yozishni ham) o‘rgatdi. U insonga bilmagan narsalarini bildirdi” (Alaq surasi, 1-5-oyatlar) ",
  " “Ey, (liboslariga) burkanib olgan kishi (Muhammad!)” (Muddassir surasi, 1-oyat)",
  "“Turing-da, (insonlarni oxirat to‘g‘risida) ogohlantiring” (Muddassir surasi, 2-oyat) ",
  "Ana, endi bugun, diningizni kamoliga yetkazdim, ne'matimni tamomila berdim va sizlar uchun Islomni din bo‘lishiga rozi bo‘ldim” (Moida surasi, 3-oyat) ",
  "“(Ey, Muhammad!) Sizdan fatvo so‘raydilar. Ayting: “Alloh sizlarga otasi ham, farzandi ham bo‘lmagan odam to‘g‘risida (shunday) fatvo beradi: agar farzandsiz bo‘lgan bir erkak halok bo‘lsa (o‘lsa), agar singlisi (qolgan) bo‘lsa, qoldirgan merosning yarmini olur. Agar singlisining farzandi bo‘lmasa, u (akasi) merosxo‘r bo‘lur. Agar (singillar) ikkita bo‘lsa, ularga (aka) qoldirgan narsaning uchdan ikkisi (tegur). Agar (merosxo‘rlar) aka-uka va opa-singillar bo‘lsa, (har) bir erkakka ikki ayol hissasi (berilur). Yanglishib ketmasliklaringiz uchun Alloh sizlarga (meros hukmlarini O‘zi) bayon etadi. Alloh har bir narsani biluvchi zotdir” (Niso surasi, 176-oyat)",
  "“(Ey, Muhammad!) Qachonki, Allohning nusrati (madadi) va g‘alaba kelganida, odamlar to‘p-to‘p bo‘lib, Allohning dini (Islom)ga kirayotganlarini ko‘rganingizda, darhol Rabbingizga hamd bilan tasbeh ayting va Undan mag‘firat so‘rang! Zero, U tavbalarni qabul etuvchi zotdir” (Nasr surasi, 1-3-oyatlar)",
  "Уларнинг (асалариларнинг) қоринларидан ранго-ранг бир ичимлик (асал шарбати) чиқадики, у инсонлар учун шифо (манбаъи)дир. Албатта, бунда тафаккур қиладиган қавм учун ибрат (ва Аллоҳнинг қудратига ишорат) бордир (Наҳл сураси, 69-оят).",
  "Эй инсонлар! Раббингиздан сизларга бир насиҳат, диллардаги нарсаларга (ёмон туйғулар, шаҳват, ботил ақида, дард ва қийноқларга) шифо ҳамда мўъминларга (тўғри йўлни кўрсатувчи) ҳидоят ва раҳмат (бўлган Қуръон) келди (Юнус сураси, 57-оят). ",
  "(Аллоҳ) мўъминлар жамоасининг кўнгилларига шифо (ҳузур-ҳаловат) бергай (Тавба сураси, 14-оят).",
  "(Эй Расулим! Уларга) айтинг: «У (Қуръон) иймон келтирганлар учун ҳидоят (тўғри йўлни кўрсатувчи раҳнамо) ва шифодир (Фуссилат сураси, 44-оят).  ",
  "Бемор бўлган вақтимда менга шифо бергувчи У (Аллоҳ)дир (Шуъаро сураси, 80-оят).",
  "Биз Қуръондан мўъминлар учун (руҳий ва баданий касалликларига) шифо ва раҳмат бўладиган нарсаларни нозил қилурмиз (Исро сураси, 82-оят). ",
  "Qasamki, sizlar uning (ilohiy vahiy ekanligi haqidagi) xabarini (ozgina) vaqtdan so'ng (Qiyomat kuni), albatta, bilursizlar",
  "(Ushbu Qur'on) qodir va hakim - Alloh (tomoni)dan nozil qilingan Kitobdir",
  "Agar sizlar kofir bo'lsangizlar, bas, albatta, Alloh sizlardan behojatdir. U O'z bandalarining kofir bo'lishiga rozi bo'lmas. Agar shukr qilsangizlar (va imon keltirsangizlar) U sizlar uchun rozi bo'lur. Hech bir ko'taruvchi (gunohkor) o'zga (ko'taruvchi)ning yukini (gunohini) ko'tarmas. So'ngra qaytishlaringiz Rabbingiz huzurigadir. Bas, U sizlarga qilib o'tgan amallaringiz xabarini berur. Albatta, U dillardagi sirlarni biluvchidir.",
  "(Ey, Muhammad), Mening imon keltirgan bandalarimga ayting: 'Parvardigoringizdan qo'rqingiz! Bu dunyoda ezgu ish qilgan zotlar uchun (oxiratda) chiroyli (oqibat - jannat) bordir. Allohning yeri kengdir. Albatta, sabr qiluvchilarga mukofotlari behisob berilur",
  "Va albatta U zot otilib chiqadigan nutfadan erkak-ayol juftlarni yaratgandir.",
  "Qiyomat) soati yaqinlashib qoldi va oy ham bo‘lindi.",
  "Shunda u Parvardigoriga: «Men (u kofir qavmimdan) mag‘lubdirman. O’zing yordam qilgin», deb duo-iltijo qilgan edi.",
  "Albatta Biz ularni imtihon qilish uchun bir tuya yuborguvchidirmiz. Bas, (ey Solih), sen (ularning qilmishlarini) kuzatib va (ozor-aziyyatlariga) sabr qilib turavergin!",
  "Avval o‘tib ketgan ota-bobolarimiz ham-a?! »",
  "Va derlar: «Bu faqat ochiq-ravshan sehrdir.",
  "Sizlar faqat qilib o‘tgan jinoyatlaringiz sababli jazolanursizlar.  ",
  "U (menga) «Rostdan ham sen (o‘lganimizdan so‘ng yana qayta tirilishimizni) tasdiq etguvchilardanmisan? Bizlar o‘lib, tuproq va suyaklarga aylanib ketgan vaqtimizda haqiqatan ham (qayta tiriltirilib) jazolanguchimizmi?» der edi.",
  "So‘ng o‘zi qarab uni do‘zaxning o‘rtasida ko‘rgach;",
  "Agar Parvardigorimning ne’mati (ya’ni hidoyati) bo‘lmasa edi, albatta men (sen bilan birga do‘zaxga) hozir qilinguvchilardan bo‘lur edim.",
  " (Qani menga aytgin-chi) bizlar faqat birinchi o‘limimizdan boshqa o‘lguvchi emas ekanmizmi?! (Bir marta o‘lganimizdan so‘ng tirilib) azoblanguvchi emas ekanmizmi?",
];
