  export const chapters = [
  {
    id: 1,
    name: "الفاتحة",
    transliteration: "Al-Fatihah",
    translation: "Открывающая Коран",
    type: "meccan",
    total_verses: 7,
    verses: 'Вторая сура Священного Корана «Аль-Бакара» (в переводе с арабского – «Корова») относится к мединскому периоду жизни Пророка Мухаммада (с.г.в.). Это самая длинная сура в Коране – в ней 286 аятов.

    Аллах ниспослал аяты «Коровы» после хиджры Посланника Всевышнего (с.г.в.) в Медину. Начало её текста является своего рода продолжением первой, «открывающей» суры Корана «Аль-Фатиха». Здесь более подробно раскрываются мысли, изложенные в предыдущей суре. «Аль-Бакара» напоминает нам о том, что только Коран является основным руководством для мусульман. В суре рассказывается о тех благах, которые Аллах своей милостью даровал верующим.
    
    Также в аятах подробно описана и участь безбожников. В первой части суры упомянуты три категории людей:
    
    Остерегающиеся (богобоязненные): те, кто истинно верят в Аллаха. Они верят в Его знамения, в Судный день и каждодневно совершают благие дела, дабы обрести Его милость.
    Неверующие: те, кто не признают Аллаха. Эта категория людей полностью отрицает Его существование.
    Лицемеры.
    Наверное, самая страшная категория из всех. Они делают вид, что верят, однако поступки доказывают обратное. И иман у этих людей очень слаб. Около половины суры отведено повествованию о стараниях Ибрахима и Исмаила (а.с.) в строительстве Каабы. Это служит напоминанием и для верующих. Предупреждает о том, что нужно неоднократно думать, прежде чем совершать те или иные деяния.
    
    В «Бакаре» также идёт речь о единобожии и о тех знамениях Творца, которые подтверждают это. Говорится о недопустимости многобожия, о запретной к приёму верующими пище и т.д. Содержатся наставления Всевышнего относительно жизни и быта мусульманина: что такое пост, как делится имущество, вопросы завещания и многое другое. Описаны процедуры брака и развода, обстоятельства и порядок их совершения, права и обязанности мужчины и женщины.
    
    Все эти аяты призваны наставить человека на путь истинный. Чтобы он провёл свою жизнь правильно и праведно. Суру завершает мольба верующих, обращённая к Всевышнему. Они просят поддержки у Аллаха в борьбе против неверия. В то же время 256-й аят гласит: «Нет принуждения в религии», т.е. в ислам нельзя обращать людей насильно.
    
    В суре «Бакара» выделено три постулата. На них и основывается религия мусульман. Первый из них – безусловное признание Всевышнего. Второй – вера в День воскресения и Суд. Третий же постулат – благодеяния.
    
    Для того чтобы верить в Аллаха, как оно было ниспослано в Коране Пророку ислама (с.г.в.), необходимо единство людей, их согласие. Иначе умму ожидает раскол. Известно много хадисов, рассказывающих о значимости суры «Корова».
    
    Например, в хадисе Муслима содержится интересная фраза, что «Шайтан бежит из дома, где читается «Аль-Бакара» (Муслим, 1/539). В другом хадисе этот же смысл передан в другой трактовке и упоминается, как Посланник Аллаха (с.г.в.) однажды сказал: «Читайте суру «Аль-Бакара в своих домах, и шайтан не войдёт». (Аль-Хаким, 1/561).
    
    Особенным значением для всех верующих обладает 255-й аят «Бакары», который получил название «Аятуль-Курси», (Аят «аль-Курси», Аят Трона). Его обычно читают после завершения намаза перед 33-кратным произнесением зикров «Субхан Аллах!», «АльхамдулиЛлях!» и «Аллаху Акбар!»'
  },
  {
    id: 2,
    name: "البقرة",
    transliteration: "Al-Baqarah",
    translation: "Корова",
    type: "medinan",
    total_verses: 286,
  },
  {
    id: 3,
    name: "آل عمران",
    transliteration: "Ali 'Imran",
    translation: "Семейство Имрана",
    type: "medinan",
    total_verses: 200,
  },
  {
    id: 4,
    name: "النساء",
    transliteration: "An-Nisa",
    translation: "Женщины",
    type: "medinan",
    total_verses: 176,
  },
  {
    id: 5,
    name: "المائدة",
    transliteration: "Al-Ma'idah",
    translation: "Трапеза",
    type: "medinan",
    total_verses: 120,
  },
  {
    id: 6,
    name: "الأنعام",
    transliteration: "Al-An'am",
    translation: "Скот",
    type: "meccan",
    total_verses: 165,
  },
  {
    id: 7,
    name: "الأعراف",
    transliteration: "Al-A'raf",
    translation: "Ограды",
    type: "meccan",
    total_verses: 206,
  },
  {
    id: 8,
    name: "الأنفال",
    transliteration: "Al-Anfal",
    translation: "Трофеи",
    type: "medinan",
    total_verses: 75,
  },
  {
    id: 9,
    name: "التوبة",
    transliteration: "At-Tawbah",
    translation: "Покаяние",
    type: "medinan",
    total_verses: 129,
  },
  {
    id: 10,
    name: "يونس",
    transliteration: "Yunus",
    translation: "Йунус",
    type: "meccan",
    total_verses: 109,
  },
  {
    id: 11,
    name: "هود",
    transliteration: "Hud",
    translation: "Худ",
    type: "meccan",
    total_verses: 123,
  },
  {
    id: 12,
    name: "يوسف",
    transliteration: "Yusuf",
    translation: "Йусуф",
    type: "meccan",
    total_verses: 111,
  },
  {
    id: 13,
    name: "الرعد",
    transliteration: "Ar-Ra'd",
    translation: "Гром",
    type: "medinan",
    total_verses: 43,
  },
  {
    id: 14,
    name: "ابراهيم",
    transliteration: "Ibrahim",
    translation: "Ибрахим",
    type: "meccan",
    total_verses: 52,
  },
  {
    id: 15,
    name: "الحجر",
    transliteration: "Al-Hijr",
    translation: "Хиджр ",
    type: "meccan",
    total_verses: 99,
  },
  {
    id: 16,
    name: "النحل",
    transliteration: "An-Nahl",
    translation: "Пчелы",
    type: "meccan",
    total_verses: 128,
  },
  {
    id: 17,
    name: "الإسراء",
    transliteration: "Al-Isra",
    translation: "Ночной перенос",
    type: "meccan",
    total_verses: 111,
  },
  {
    id: 18,
    name: "الكهف",
    transliteration: "Al-Kahf",
    translation: "Пещера",
    type: "meccan",
    total_verses: 110,
  },
  {
    id: 19,
    name: "مريم",
    transliteration: "Maryam",
    translation: "Марьям",
    type: "meccan",
    total_verses: 98,
  },
  {
    id: 20,
    name: "طه",
    transliteration: "Taha",
    translation: "Та Ха ",
    type: "meccan",
    total_verses: 135,
  },
  {
    id: 21,
    name: "الأنبياء",
    transliteration: "Al-Anbya",
    translation: "Пророки",
    type: "meccan",
    total_verses: 112,
  },
  {
    id: 22,
    name: "الحج",
    transliteration: "Al-Hajj",
    translation: "Паломничество",
    type: "medinan",
    total_verses: 78,
  },
  {
    id: 23,
    name: "المؤمنون",
    transliteration: "Al-Mu'minun",
    translation: "Верующие",
    type: "meccan",
    total_verses: 118,
  },
  {
    id: 24,
    name: "النور",
    transliteration: "An-Nur",
    translation: "Свет",
    type: "medinan",
    total_verses: 64,
  },
  {
    id: 25,
    name: "الفرقان",
    transliteration: "Al-Furqan",
    translation: "аль-Фуркан",
    type: "meccan",
    total_verses: 77,
  },
  {
    id: 26,
    name: "الشعراء",
    transliteration: "Ash-Shu'ara",
    translation: "Поэты",
    type: "meccan",
    total_verses: 227,
  },
  {
    id: 27,
    name: "النمل",
    transliteration: "An-Naml",
    translation: "Муравьи",
    type: "meccan",
    total_verses: 93,
  },
  {
    id: 28,
    name: "القصص",
    transliteration: "Al-Qasas",
    translation: "Рассказ",
    type: "meccan",
    total_verses: 88,
  },
  {
    id: 29,
    name: "العنكبوت",
    transliteration: "Al-'Ankabut",
    translation: "Паук",
    type: "meccan",
    total_verses: 69,
  },
  {
    id: 30,
    name: "الروم",
    transliteration: "Ar-Rum",
    translation: "Римляне",
    type: "meccan",
    total_verses: 60,
  },
  {
    id: 31,
    name: "لقمان",
    transliteration: "Luqman",
    translation: "Лукман",
    type: "meccan",
    total_verses: 34,
  },
  {
    id: 32,
    name: "السجدة",
    transliteration: "As-Sajdah",
    translation: "Земной поклон",
    type: "meccan",
    total_verses: 30,
  },
  {
    id: 33,
    name: "الأحزاب",
    transliteration: "Al-Ahzab",
    translation: "Союзники",
    type: "medinan",
    total_verses: 73,
  },
  {
    id: 34,
    name: "سبإ",
    transliteration: "Saba",
    translation: "Сава",
    type: "meccan",
    total_verses: 54,
  },
  {
    id: 35,
    name: "فاطر",
    transliteration: "Fatir",
    translation: "Творец",
    type: "meccan",
    total_verses: 45,
  },
  {
    id: 36,
    name: "يس",
    transliteration: "Ya-Sin",
    translation: "Йа Син",
    type: "meccan",
    total_verses: 83,
  },
  {
    id: 37,
    name: "الصافات",
    transliteration: "As-Saffat",
    translation: "Выстроившиеся в ряды",
    type: "meccan",
    total_verses: 182,
  },
  {
    id: 38,
    name: "ص",
    transliteration: "Sad",
    translation: "Сод",
    type: "meccan",
    total_verses: 88,
  },
  {
    id: 39,
    name: "الزمر",
    transliteration: "Az-Zumar",
    translation: "Толпы",
    type: "meccan",
    total_verses: 75,
  },
  {
    id: 40,
    name: "غافر",
    transliteration: "Ghafir",
    translation: "Прощающий",
    type: "meccan",
    total_verses: 85,
  },
  {
    id: 41,
    name: "فصلت",
    transliteration: "Fussilat",
    translation: "Разъяснены",
    type: "meccan",
    total_verses: 54,
  },
  {
    id: 42,
    name: "الشورى",
    transliteration: "Ash-Shuraa",
    translation: "Совет",
    type: "meccan",
    total_verses: 53,
  },
  {
    id: 43,
    name: "الزخرف",
    transliteration: "Az-Zukhruf",
    translation: "Украшения",
    type: "meccan",
    total_verses: 89,
  },
  {
    id: 44,
    name: "الدخان",
    transliteration: "Ad-Dukhan",
    translation: "Дым",
    type: "meccan",
    total_verses: 59,
  },
  {
    id: 45,
    name: "الجاثية",
    transliteration: "Al-Jathiyah",
    translation: "Коленопреклоненные",
    type: "meccan",
    total_verses: 37,
  },
  {
    id: 46,
    name: "الأحقاف",
    transliteration: "Al-Ahqaf",
    translation: "Барханы",
    type: "meccan",
    total_verses: 35,
  },
  {
    id: 47,
    name: "محمد",
    transliteration: "Muhammad",
    translation: "Мухаммад",
    type: "medinan",
    total_verses: 38,
  },
  {
    id: 48,
    name: "الفتح",
    transliteration: "Al-Fath",
    translation: "Победа",
    type: "medinan",
    total_verses: 29,
  },
  {
    id: 49,
    name: "الحجرات",
    transliteration: "Al-Hujurat",
    translation: "Комнаты",
    type: "medinan",
    total_verses: 18,
  },
  {
    id: 50,
    name: "ق",
    transliteration: "Qaf",
    translation: "Каф",
    type: "meccan",
    total_verses: 45,
  },
  {
    id: 51,
    name: "الذاريات",
    transliteration: "Adh-Dhariyat",
    translation: "Рассеивающие прах",
    type: "meccan",
    total_verses: 60,
  },
  {
    id: 52,
    name: "الطور",
    transliteration: "At-Tur",
    translation: "Гора",
    type: "meccan",
    total_verses: 49,
  },
  {
    id: 53,
    name: "النجم",
    transliteration: "An-Najm",
    translation: "Звезда",
    type: "meccan",
    total_verses: 62,
  },
  {
    id: 54,
    name: "القمر",
    transliteration: "Al-Qamar",
    translation: "Месяц",
    type: "meccan",
    total_verses: 55,
  },
  {
    id: 55,
    name: "الرحمن",
    transliteration: "Ar-Rahman",
    translation: "Милостивый",
    type: "medinan",
    total_verses: 78,
  },
  {
    id: 56,
    name: "الواقعة",
    transliteration: "Al-Waqi'ah",
    translation: "Событие",
    type: "meccan",
    total_verses: 96,
  },
  {
    id: 57,
    name: "الحديد",
    transliteration: "Al-Hadid",
    translation: "Железо",
    type: "medinan",
    total_verses: 29,
  },
  {
    id: 58,
    name: "المجادلة",
    transliteration: "Al-Mujadila",
    translation: "Препирающаяся",
    type: "medinan",
    total_verses: 22,
  },
  {
    id: 59,
    name: "الحشر",
    transliteration: "Al-Hashr",
    translation: "Сбор",
    type: "medinan",
    total_verses: 24,
  },
  {
    id: 60,
    name: "الممتحنة",
    transliteration: "Al-Mumtahanah",
    translation: "Испытуемая",
    type: "medinan",
    total_verses: 13,
  },
  {
    id: 61,
    name: "الصف",
    transliteration: "As-Saf",
    translation: "Ряды",
    type: "medinan",
    total_verses: 14,
  },
  {
    id: 62,
    name: "الجمعة",
    transliteration: "Al-Jumu'ah",
    translation: "Собрание",
    type: "medinan",
    total_verses: 11,
  },
  {
    id: 63,
    name: "المنافقون",
    transliteration: "Al-Munafiqun",
    translation: "Лицемеры",
    type: "medinan",
    total_verses: 11,
  },
  {
    id: 64,
    name: "التغابن",
    transliteration: "At-Taghabun",
    translation: "Взаимное обделение",
    type: "medinan",
    total_verses: 18,
  },
  {
    id: 65,
    name: "الطلاق",
    transliteration: "At-Talaq",
    translation: "Развод",
    type: "medinan",
    total_verses: 12,
  },
  {
    id: 66,
    name: "التحريم",
    transliteration: "At-Tahrim",
    translation: "Запрещение",
    type: "medinan",
    total_verses: 12,
  },
  {
    id: 67,
    name: "الملك",
    transliteration: "Al-Mulk",
    translation: "Власть",
    type: "meccan",
    total_verses: 30,
  },
  {
    id: 68,
    name: "القلم",
    transliteration: "Al-Qalam",
    translation: "Письменная трость",
    type: "meccan",
    total_verses: 52,
  },
  {
    id: 69,
    name: "الحاقة",
    transliteration: "Al-Haqqah",
    translation: "Неминуемое",
    type: "meccan",
    total_verses: 52,
  },
  {
    id: 70,
    name: "المعارج",
    transliteration: "Al-Ma'arij",
    translation: "Ступени",
    type: "meccan",
    total_verses: 44,
  },
  {
    id: 71,
    name: "نوح",
    transliteration: "Nuh",
    translation: "Нух",
    type: "meccan",
    total_verses: 28,
  },
  {
    id: 72,
    name: "الجن",
    transliteration: "Al-Jinn",
    translation: "Джинны",
    type: "meccan",
    total_verses: 28,
  },
  {
    id: 73,
    name: "المزمل",
    transliteration: "Al-Muzzammil",
    translation: "Закутавшийся",
    type: "meccan",
    total_verses: 20,
  },
  {
    id: 74,
    name: "المدثر",
    transliteration: "Al-Muddaththir",
    translation: "Завернувшийся",
    type: "meccan",
    total_verses: 56,
  },
  {
    id: 75,
    name: "القيامة",
    transliteration: "Al-Qiyamah",
    translation: "Воскресение",
    type: "meccan",
    total_verses: 40,
  },
  {
    id: 76,
    name: "الانسان",
    transliteration: "Al-Insan",
    translation: "Человек",
    type: "medinan",
    total_verses: 31,
  },
  {
    id: 77,
    name: "المرسلات",
    transliteration: "Al-Mursalat",
    translation: "Посылаемые",
    type: "meccan",
    total_verses: 50,
  },
  {
    id: 78,
    name: "النبإ",
    transliteration: "An-Naba",
    translation: "Весть",
    type: "meccan",
    total_verses: 40,
  },
  {
    id: 79,
    name: "النازعات",
    transliteration: "An-Nazi'at",
    translation: "Исторгающие",
    type: "meccan",
    total_verses: 46,
  },
  {
    id: 80,
    name: "عبس",
    transliteration: "'Abasa",
    translation: "Нахмурился",
    type: "meccan",
    total_verses: 42,
  },
  {
    id: 81,
    name: "التكوير",
    transliteration: "At-Takwir",
    translation: "Скручивание",
    type: "meccan",
    total_verses: 29,
  },
  {
    id: 82,
    name: "الإنفطار",
    transliteration: "Al-Infitar",
    translation: "Раскалывание",
    type: "meccan",
    total_verses: 19,
  },
  {
    id: 83,
    name: "المطففين",
    transliteration: "Al-Mutaffifin",
    translation: "Обвешивающие",
    type: "meccan",
    total_verses: 36,
  },
  {
    id: 84,
    name: "الإنشقاق",
    transliteration: "Al-Inshiqaq",
    translation: "Разверзнется",
    type: "meccan",
    total_verses: 25,
  },
  {
    id: 85,
    name: "البروج",
    transliteration: "Al-Buruj",
    translation: "Созвездия Зодиака",
    type: "meccan",
    total_verses: 22,
  },
  {
    id: 86,
    name: "الطارق",
    transliteration: "At-Tariq",
    translation: "Ночной путник",
    type: "meccan",
    total_verses: 17,
  },
  {
    id: 87,
    name: "الأعلى",
    transliteration: "Al-A'la",
    translation: "Всевышний",
    type: "meccan",
    total_verses: 19,
  },
  {
    id: 88,
    name: "الغاشية",
    transliteration: "Al-Ghashiyah",
    translation: "Покрывающее",
    type: "meccan",
    total_verses: 26,
  },
  {
    id: 89,
    name: "الفجر",
    transliteration: "Al-Fajr",
    translation: "Заря",
    type: "meccan",
    total_verses: 30,
  },
  {
    id: 90,
    name: "البلد",
    transliteration: "Al-Balad",
    translation: "Город",
    type: "meccan",
    total_verses: 20,
  },
  {
    id: 91,
    name: "الشمس",
    transliteration: "Ash-Shams",
    translation: "Солнце",
    type: "meccan",
    total_verses: 15,
  },
  {
    id: 92,
    name: "الليل",
    transliteration: "Al-Layl",
    translation: "Ночь",
    type: "meccan",
    total_verses: 21,
  },
  {
    id: 93,
    name: "الضحى",
    transliteration: "Ad-Duhaa",
    translation: "Утро",
    type: "meccan",
    total_verses: 11,
  },
  {
    id: 94,
    name: "الشرح",
    transliteration: "Ash-Sharh",
    translation: "Раскрытие",
    type: "meccan",
    total_verses: 8,
  },
  {
    id: 95,
    name: "التين",
    transliteration: "At-Tin",
    translation: "Смоковница",
    type: "meccan",
    total_verses: 8,
  },
  {
    id: 96,
    name: "العلق",
    transliteration: "Al-'Alaq",
    translation: "Сгусток крови",
    type: "meccan",
    total_verses: 19,
  },
  {
    id: 97,
    name: "القدر",
    transliteration: "Al-Qadr",
    translation: "Предопределение",
    type: "meccan",
    total_verses: 5,
  },
  {
    id: 98,
    name: "البينة",
    transliteration: "Al-Bayyinah",
    translation: "Ясное знамение",
    type: "medinan",
    total_verses: 8,
  },
  {
    id: 99,
    name: "الزلزلة",
    transliteration: "Az-Zalzalah",
    translation: "Сотрясение",
    type: "medinan",
    total_verses: 8,
  },
  {
    id: 100,
    name: "العاديات",
    transliteration: "Al-'Adiyat",
    translation: "Скачущие",
    type: "meccan",
    total_verses: 11,
  },
  {
    id: 101,
    name: "القارعة",
    transliteration: "Al-Qari'ah",
    translation: "Великое бедствие",
    type: "meccan",
    total_verses: 11,
  },
  {
    id: 102,
    name: "التكاثر",
    transliteration: "At-Takathur",
    translation: "Страсть к приумножению",
    type: "meccan",
    total_verses: 8,
  },
  {
    id: 103,
    name: "العصر",
    transliteration: "Al-'Asr",
    translation: "Предвечернее время",
    type: "meccan",
    total_verses: 3,
  },
  {
    id: 104,
    name: "الهمزة",
    transliteration: "Al-Humazah",
    translation: "Хулитель",
    type: "meccan",
    total_verses: 9,
  },
  {
    id: 105,
    name: "الفيل",
    transliteration: "Al-Fil",
    translation: "Слон",
    type: "meccan",
    total_verses: 5,
  },
  {
    id: 106,
    name: "قريش",
    transliteration: "Quraysh",
    translation: "Курейшиты",
    type: "meccan",
    total_verses: 4,
  },
  {
    id: 107,
    name: "الماعون",
    transliteration: "Al-Ma'un",
    translation: "Мелочь",
    type: "meccan",
    total_verses: 7,
  },
  {
    id: 108,
    name: "الكوثر",
    transliteration: "Al-Kawthar",
    translation: "Изобилие",
    type: "meccan",
    total_verses: 3,
  },
  {
    id: 109,
    name: "الكافرون",
    transliteration: "Al-Kafirun",
    translation: "Неверующие",
    type: "meccan",
    total_verses: 6,
  },
  {
    id: 110,
    name: "النصر",
    transliteration: "An-Nasr",
    translation: "Помощь",
    type: "medinan",
    total_verses: 3,
  },
  {
    id: 111,
    name: "المسد",
    transliteration: "Al-Masad",
    translation: "Пальмовые волокна",
    type: "meccan",
    total_verses: 5,
  },
  {
    id: 112,
    name: "الإخلاص",
    transliteration: "Al-Ikhlas",
    translation: "Очищение веры",
    type: "meccan",
    total_verses: 4,
  },
  {
    id: 113,
    name: "الفلق",
    transliteration: "Al-Falaq",
    translation: "Рассвет",
    type: "meccan",
    total_verses: 5,
  },
  {
    id: 114,
    name: "الناس",
    transliteration: "An-Nas",
    translation: "Люди",
    type: "meccan",
    total_verses: 6,
  },
];
